### ISSUE TITLE
Support for nested JSON

### ISSUE THREAD

**Issue by sharmajnu** [biesbjerg/ng2-translate-extract#11]
We are using nested JSON to organize the translation keys in a better way. But ng2-translate-extract is not supporting nested JSON.  Following is an example from html and nested JSON.
 <h3>{{'PAGES.SHARED.MeetingNotFound' | translate}}</h3>

What I want that this tool should produce JSON like this
{
  PAGES: {
       SHARED: {
         "MeetingNotFound":  "MeetingNotFound"
       }
 }

Is this possible?

**Comment by biesbjerg** [comment]
I'm not sure this can be implemented.

How would we tell the difference between `PAGES.SHARED.MeetingNotFound` which we want nested and `STRING.WITH.DOTS` which we wouldn't want nested?

**Comment by sharmajnu** [comment]
Could it be implemented with a switch? In a large project it will be really difficult to manage all the keys if they are at the same level. A switch which treats DOT(.) as nested structure would be idle and the default functionality could be as it is today. what do you think about that?

**Comment by biesbjerg** [comment]
Supporting nested JSON means way more complex code to handle merging of strings and we would have to introduce a CLI argument that only applies to JSON format, making the tool more complicated to use, understand and maintain.

You can use the dot structure you do now in combination with the just added --sort argument to sort keys alphabetically. That way your translations are still grouped in the translation file. Personally I think that's Good Enough™.

Alternatively you could write a custom script to post process your translations to convert dot keys to nested JSON.

**Comment by biesbjerg** [comment]
I'm going to keep this issue open while I think about other options.

**Comment by biesbjerg** [comment]
I think we could add a new format/compiler. A NestedJsonCompiler that flattens strings on parse and unflattens on compile.

Used via ng2-translate-extract ... --format=nested-json

**Comment by sharmajnu** [comment]
Thanks, that would be good.

**Comment by biesbjerg** [comment]
Closed via https://github.com/biesbjerg/ng2-translate-extract/commit/7822916e282f82f775674683399ddadd97dcd9f7
