### ISSUE TITLE
Sorting not working(?)

### ISSUE THREAD

**Issue by Mwoagh** [biesbjerg/ng2-translate-extract#16]
I am using version 0.6.0
The sorting was working at first but when the file got bigger it started moving the keys out of order. 

Note: I tried both "json" and "namespaced-json"

This is what my command looks like (from package.json):
    "extract-en": "ng2-translate-extract --dir ./src/app --sort --output ./src/i18n/en-US.json --format=json"

Gives the following unsorted output (I only included the beginning of the output):
{
	"SYSTEM.DETAILS.LICENSES_TITLE": "",
	"SYSTEM.LIST.TITLE": "",
	"OPERATOR.LIST.COLUMN_EMAIL": "",
	"COMMON.ERROR.FAILED_TO_LOAD_LIST": "",
	"SYSTEM.DETAILS.LICENSES_COLUMN_MODULE_NAME": "",
	"COMMON.ERROR.FIELD_IS_MANDATORY": "",
	"INSTANCE.LIST.COLUMN_NAME": "",
	"SYSTEM.DETAILS.FORM_TITLE": "",
	"LICENSE.DIALOG.CHOOSE_MODULE": "",
...

**Comment by biesbjerg** [comment]
@gustavgahm Any chance you've experienced something similar?

**Comment by gustavgahm** [comment]
Actualy I have. The problem seems to be with _Object.assign_ in _TranslationCollection.add_. I do not know why this happen though. Do you have any idea?

```
public add(key: string, val: string = ''): TranslationCollection {
	return new TranslationCollection(Object.assign({}, this.values, { [key]: val }));
}
```

If i change the function like below it will work:
```
public add(key: string, val: string = ''): TranslationCollection {

	let values: TranslationType = {};

	for (var k in this.values) {
		if (this.values.hasOwnProperty(key)) {
			values[k] = this.values[k];
		}
	}

	values[key] = val;

	return new TranslationCollection(values);
}
```

**Comment by biesbjerg** [comment]
Please try the new package: https://www.npmjs.com/package/@biesbjerg/ngx-translate-extract

**Comment by Mwoagh** [comment]
Ok, thank you!

/Bas
