### ISSUE TITLE
Extract from JS not working

### ISSUE THREAD

**Issue by Nostrus** [biesbjerg/ng2-translate-extract#21]
Hello,

I started using your tool, and it seems to work mostly flawless with HTML, but I don't see any strings coming from JavaScript.

I'm using it in the simple way of for example ` this.translate.get('Getting your location...')`

where `this.translate` is `public translate: TranslateService`

Am I missing something?

**Comment by biesbjerg** [comment]
Unfortunately this tool only extracts strings from typescript files. The reason is I want to switch away from regular expressions and extract strings using the Typescript parser.

**Comment by Nostrus** [comment]
My bad...I'm actually using TypeScript with Ionic 2. (I was just thinking of "script files" as opposed to HTML files.)

**Comment by biesbjerg** [comment]
That's weird. There are passing tests covering your simple use case. What command are you running to extract the strings? Sure the input dir is correct?

**Comment by Nostrus** [comment]
I did everything according to the docs. Gave it another try and found the bug now, it is because I'm running the command with a new line in it, as such:
```
this.translate
    .get('Uploading image')
```

Once I removed the new line it worked fine. Could you enhance your script to cater for this, please? :)

**Comment by biesbjerg** [comment]
Please the experimental ast parser (-e flag). It should be more robust but needs more testing.

**Comment by Nostrus** [comment]
Yep, this solved it, thanks, and keep up the good work :)

**Comment by biesbjerg** [comment]
Nice:-)
