### ISSUE TITLE
Add sorting of translations in json file

### ISSUE THREAD

**Issue by gustavgahm** [biesbjerg/ng2-translate-extract#8]
I would very much like a feature that sorts translations in the json file by key. What do you think about a feature like this?

`{
 "FirstName": "名",
 "LastName": "姓氏"",
 "Address": "地址"
}`

would become

`{
 "Address": "地址",
 "FirstName": "名",
 "LastName": "姓氏""
}`

**Comment by biesbjerg** [comment]
Personally I prefer to keep the order of extracted keys. The chance of related keys being grouped/close together is better.

Can you explain your use case? What does sorting the strings solve / make easier?

**Comment by gustavgahm** [comment]
We prefer to group our translations by meaning and not by the order they appear in the code.

For example it would be nice if translations starting with "Product" would be grouped and translations starting with "Order" would be grouped. 

Our json file will contain many translations and if all translations appear in alphabetical order it will be easier for our translators to find and navigate in the file.

Maybe it could be added as an option?

**Comment by biesbjerg** [comment]
I'm using an external translation service with the `pot` format, so I haven't seen the need to sort keys, but I see how it could be useful.

It should be easy enough to add a `sort` method to `TranslationCollection` class and an option to the CLI (defaulting to false).

**Comment by gustavgahm** [comment]
Commit a pull request for this: #9

**Comment by biesbjerg** [comment]
Thank you for the PR!

Merged and published new package to npm registry!
